### ISSUE TITLE
CGO 크로스 컴파일 환경 지원

### ISSUE THREAD

**Issue by djinchung** [fatima-go/gofar#15]
**AS-IS**
현재 크로스 컴파일시에 CC 는 공통으로 사용중에 있다.
따라서 타켓 환경이 amd64와 arm64등이 같이 있는 경우 제대로 컴파일이 안되는 상황이 발생한다.
각 환경별로 별도의 CC 를 지정할 수 있는 방법을 제공한다.

```shell
dave_01@dave-MacBook-Pro-14 uptnd % gofar uptnd x86_64-pc-linux-gcc
--------------------------------------------------
project base dir : /Users/dave_01/IronForge/gowork/src/tflo/be-tflo-uptnd
resource dir : /Users/dave_01/IronForge/gowork/src/tflo/be-tflo-uptnd/resources
expose process name : uptnd
binary : uptnd
--------------------------------------------------
working directory : /var/folders/n4/0wrj73vn2559m2bgm8b279800000gn/T/uptnd3691214792

>> compiling uptnd...
CC=x86_64-pc-linux-gcc GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 go build -o /var/folders/n4/0wrj73vn2559m2bgm8b279800000gn/T/uptnd3691214792/platform/darwin_arm64/uptnd -ldflags='-s -w'
fail to execute command : exit status 1
# runtime/cgo
x86_64-pc-linux-gcc: error: arm64: No such file or directory
x86_64-pc-linux-gcc: error: unrecognized command line option '-arch'
```

--

**TO-BE**
아래와 같이 platform 별 cc 항목을 추가해서 운영한다
```yaml
---
# if you want to check platform support list, use below command
# $ go tool dist list
#
platform_list:
  - os: linux
    arch: amd64
    cc: x86_64-pc-linux-gcc
  - os: linux
    arch: arm64
    cc: aarch64-unknown-linux-gnu-gcc
  - os: darwin
    arch: arm64
```

```shell
# linux_amd64 컴파일시 실행 모습
CC=x86_64-pc-linux-gcc GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o ~/Downloads/uptnd
# linux_arm64 컴파일시 실행 모습
CC=aarch64-unknown-linux-gnu-gcc GOOS=linux GOARCH=arm64 CGO_ENABLED=1 go build -o ~/Downloads/uptnd -ldflags='-s -w'
```shell
